-- SPDX-License-Identifier: MIT
-- Property tests over the rebocap codec spec, using Plausible (QuickCheck for
-- Lean4).  The top-level `#eval Testable.check` lines run at build time and fail
-- the build on a counterexample; `lake exe proptest` is the CI entry point.
import Plausible
import Sinew.Protocol
open Plausible Sinew.Protocol

-- Harness smoke check (native Nat generator).
#eval Testable.check (∀ n : Nat, n < n + 1)

-- Codec property: a frame shorter than a full 36-byte frame never decodes to .ok.
-- (Generated ByteArrays from a List UInt8.)
#eval Testable.check (∀ (l : List UInt8),
  l.length < FRAME_BYTES → ¬ (parseFrame ⟨l.toArray⟩ matches .ok _))

def main : IO Unit :=
  IO.println "proptest: property checks run at build time (#eval above; build fails on a counterexample)"
